src/Msmaldi.Financeiro.Website/Entities/SwingTrade.cs
using System;
using Msmaldi.Financeiro.Website.Interfaces;

namespace Msmaldi.Financeiro.Website.Entities
{
    public class SwingTrade : ISwingTrade
    {
        public long Id { get; protected set; }
        public string Symbol { get; protected set; }
        public int Quantidade { get; protected set; }
        public double ValorDeAquisicao { get; protected set; }

        public Guid UserId { get; set; }
        public User User { get; set; }

        public Stock Stock { get; protected set; }

        public SwingTrade(string symbol, 
                             int quantidade, 
                          double valorDeAquisicao,
                            User user)
            : this(symbol, quantidade, valorDeAquisicao, user.Id)
        {
        }

        public SwingTrade(string symbol,
                             int quantidade,
                          double valorDeAquisicao,
                            Guid userId)
        {
            Symbol = symbol;
            Quantidade = quantidade;
            ValorDeAquisicao = valorDeAquisicao;
            UserId = userId;
        }

        protected SwingTrade()
        {
        }
    }
}

src/Msmaldi.Financeiro.Website/Models/SwingTradeViewModels/SwingTradeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Msmaldi.Financeiro.Website.Models.SwingTradeViewModels
{
    public class SwingTradeViewModel
    {
        public long Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Display(Name = "Código")]
        public string Symbol { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Display(Name = "Quantidade")]
        public int Quantidade { get; set; }


        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Display(Name = "Valor de Aquisição")]
        [Range(0.01, 100000.0)]
        public double ValorDeAquisicao { get; set; }
    }
}

src/Msmaldi.Financeiro.Website/Controllers/StockController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Msmaldi.Financeiro.Website.Data;
using Msmaldi.Financeiro.Website.Data.Seeders.ExternalProviders;
using Msmaldi.Financeiro.Website.Entities;
using Msmaldi.Financeiro.Website.Models.SwingTradeViewModels;

namespace Msmaldi.Financeiro.Website.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly FinanceiroDbContext _db;
        private readonly StockQuotesProvider _provider;
        public StockController(FinanceiroDbContext context)
        {
            _db = context;
            _provider = new StockQuotesProvider();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var stocks = await _db.Stocks.ToListAsync();
            return View(stocks);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewStock m)
        {
            if (!ModelState.IsValid)
                return View(m);

            
            if (await _db.Stocks.AllAsync(c => c.Symbol == m.Symbol))
            {
                ModelState.AddModelError("Symbol", "Está Ação já está cadastrada.");
                return View(m);
            }

            try
            {
                var stockQuoteDaily = await _provider.GetStockQuoteDailyAsync(m.Symbol);
                _db.Stocks.Add(new Stock(m.Symbol));
                await _db.SaveChangesAsync();
                _db.StockQuotesDaily.AddRange(stockQuoteDaily);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("Symbol", "Está Ação não foi encontrada, tente adicionar .SA ao final do código.");
                return View(m);
            }
        }

        public new void Dispose()
        {
            base.Dispose();
        } 
    }
}

src/Msmaldi.Financeiro.Website/Controllers/SwingTradesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Msmaldi.Financeiro.Website.BusinessLogic.SwingTrade;
using Msmaldi.Financeiro.Website.Data;
using Msmaldi.Financeiro.Website.Entities;
using Msmaldi.Financeiro.Website.Models.SwingTradeViewModels;

namespace Msmaldi.Financeiro.Website.Controllers
{
    [Authorize]
    public class SwingTradesController : Controller
    {
        private readonly FinanceiroDbContext _db;
        private readonly UserManager<User> _userManager;
        private readonly PosicaoConsolidadaSwingTradeFactory _swingTradePosFactory;
        
        public SwingTradesController(FinanceiroDbContext context,
            PosicaoConsolidadaSwingTradeFactory swingTradePosFactory,
          UserManager<User> userManager)
        {
            _db = context;
            _userManager = userManager;
            _swingTradePosFactory = swingTradePosFactory;
        }

        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var swingTrades = await _db.SwingTrades.AsNoTracking()
                .Where(c => c.UserId == user.Id)
                .ToListAsync();
            var posicoesSwingTrade = swingTrades
                .Select(st => _swingTradePosFactory.ObterPosicaoConsolidada(st)).ToList();

            return View(posicoesSwingTrade);
        }

        [HttpGet]
        public async Task<IActionResult>  Create()
        {
            await GetStocksAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SwingTradeViewModel m)
        {
            await GetStocksAsync();
            if (ModelState.IsValid)
            {
                var swingTrade = new SwingTrade(m.Symbol, m.Quantidade,
                    m.ValorDeAquisicao, userId: (await GetCurrentUserAsync()).Id);
                _db.SwingTrades.Add(swingTrade);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(m);
        }

        private async Task GetStocksAsync()
        {
            var stocks = await _db.Stocks.ToListAsync();
            ViewBag.Stocks = new SelectList(stocks, "Symbol", "Symbol", null);
        }

        // GET: SwingTrades/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            SwingTrade swingTrade;
            if (id == null ||
                (swingTrade = await GetSwingTradeAsync(id.Value)) == null)
                return NotFound();

            return View(swingTrade);
        }

        // POST: SwingTrades/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var swingTrade = await GetSwingTradeAsync(id);
            _db.SwingTrades.Remove(swingTrade);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<SwingTrade> GetSwingTradeAsync(long id)
        {
            var userId = (await GetCurrentUserAsync()).Id;
            return await _db.SwingTrades.Where(m => m.UserId == userId && m.Id == id).SingleOrDefaultAsync();
        }

        private Task<User> GetCurrentUserAsync()
            => _userManager.GetUserAsync(HttpContext.User);
    }
}

src/Msmaldi.Financeiro.Website/Views/SwingTrades/Create.cshtml
@model Msmaldi.Financeiro.Website.Models.SwingTradeViewModels.SwingTradeViewModel
@{ ViewData["Title"] = "Create"; }
<h2>Incluir</h2>   
<div class="row">
    <div class="col-sm-6 col-md-4">
        <form asp-action="Create">
            <div class="form-horizontal">
                <h4>Swing Trade</h4>
                <hr />
                    <p>Neste formulario, escolha a ação.</p>
                    <p>A quantidade de ações adiquiridas e o <b>preço medio das ações</b>.</p>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Symbol" class="col-sm-6 control-label"></label>
                    <div class="col-sm-6">
                        <select asp-for="Symbol" class="form-control"  asp-items="@ViewBag.Stocks"></select>
                    </div>
                    <div class="col-xs-offset-1 col-sm-offset-2">
                        <a asp-controller="Stock" asp-action="Create">O código da ação não aparece na lista, clique aqui</a>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Quantidade" class="col-sm-6 control-label"></label>
                    <div class="col-sm-6">
                        <input autofocus type="text" asp-for="Quantidade" class="form-control" />
                    </div>
                    <div class="col-xs-offset-1 col-sm-offset-2">
                        <span asp-validation-for="Quantidade" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ValorDeAquisicao" class="col-sm-6 control-label"></label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="text" asp-for="ValorDeAquisicao" class="form-control" />
                        </div>
                    </div>
                    <div class="col-xs-offset-1 col-sm-offset-2">
                        <span asp-validation-for="ValorDeAquisicao" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <input type="submit" value="Incluir" class="btn btn-default" />
                        <a asp-action="Index" class="btn btn-default">Voltar a lista</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts { @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} }

src/Msmaldi.Financeiro.Website/Views/SwingTrades/Delete.cshtml
@model Msmaldi.Financeiro.Website.Entities.SwingTrade
@{ ViewData["Title"] = "Delete"; }

<div class="row">
    <div class="col-lg-offset-4 col-lg-4 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6 col-xs-12">
        <h2>Excluir</h2>
        <h3>Voc&ecirc; quer excluir isso?</h3>
        <div>
            <hr />
            <div class="panel panel-default">
                <div class="panel-heading">
                    Swing Trade - @Model.Symbol
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        <dt>Ativo:</dt>
                        <dd>@Model.Symbol</dd>
                        <dt>Pre&ccedil;o Unit&aacute;rio:</dt>
                        <dd>@Model.ValorDeAquisicao.ToString("C2")</dd>
                        <dt>Quantidade:</dt>
                        <dd>@Model.Quantidade</dd>
                    </dl>
                </div>
            </div>
            <form asp-action="Delete">
                <div class="text-center">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-actions no-color">
                        <input type="submit" value="Sim, eu quero excluir" class="btn btn-default" />
                    </div> <hr />
                    <a asp-action="Index">Voltar a Lista</a>
                </div>
            </form>
        </div>
    </div>
</div>

src/Msmaldi.Financeiro.Website/Views/SwingTrades/Index.cshtml
@model IEnumerable<Msmaldi.Financeiro.Website.BusinessLogic.SwingTrade.PosicaoConsolidadaSwingTrade<SwingTrade>>
@{ ViewData["Title"] = "Swing Trade"; }
<h2>@ViewData["Title"]</h2>
<p><a asp-action="Create">Incluir novo</a></p>
<hr />
<div class="row">
@foreach (var item in Model)
{
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Swing Trade
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Ativo:</dt>
                    <dd>@item.SwingTrade.Symbol</dd>
                    <dt>Pre&ccedil;o Unit&aacute;rio:</dt>
                    <dd>@item.SwingTrade.ValorDeAquisicao.ToString("C")</dd>
                    <dt>Quantidade:</dt>
                    <dd>@item.SwingTrade.Quantidade</dd>
                    <dt>Valor Bruto:</dt>
                    <dd>@item.ValorBruto.ToString("C")</dd>
                    @{
                        var color = item.RendimentoBruto > 0.0 ? "color-green" :
                                    item.RendimentoBruto < 0.0 ? "color-red" : "";
                        
                        var lucroOuPrejuizo = item.RendimentoBruto > 0.0 ? "Lucro" : "Prejuízo";
                    }
                    <dt>@lucroOuPrejuizo :</dt>
                    <dd class="@color">@item.RendimentoBruto.ToString("C")</dd>
                </dl>
                <div class="text-center">
                    <a class="btn btn-default" asp-action="Delete" asp-route-id="@item.SwingTrade.Id">Excluir</a>
                </div>
            </div>
        </div>
    </div>
}
</div>