src/Msmaldi.Financeiro.Website/Controllers/CDBsComCDIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Msmaldi.Financeiro.Website.BusinessLogic.CDB;
using Msmaldi.Financeiro.Website.Data;
using Msmaldi.Financeiro.Website.Entities;
using Msmaldi.Financeiro.Website.Models.CDBComCDIViewModels;

namespace Msmaldi.Financeiro.Website.Controllers
{
    [Authorize]
    public class CDBsComCDIController : Controller
    {        
        private readonly FinanceiroDbContext _db;
        private readonly UserManager<User> _userManager;
        private readonly PosicaoConsolidadaCDBComCDIFactory _factory;

        public CDBsComCDIController(FinanceiroDbContext context,
                                      UserManager<User> userManager,
                     PosicaoConsolidadaCDBComCDIFactory factory)
        {
            _db = context;
            _userManager = userManager;
            _factory = factory;
        }

        // GET: CDBsComCDI/Create
        public async Task<IActionResult> Index()
        {
            var cdbs = await GetAllCDBsComCDIAsync();
            var posCDBs = cdbs.Select(c => _factory.ObterPosicaoConsolidada(c));
            return View(posCDBs);
        }

        // GET: CDBsComCDI/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CDBsComCDI/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CDBComCDIViewModel m)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                var cdb = new CDBComCDI(m.DataDaAplicacao,
                                        m.DataDoVencimento,
                                        m.PrecoUnitario,
                                        m.Quantidade,
                                        m.Taxa / 100.0,
                                        user);
                _db.Add(cdb);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(m);
        }

        // GET: CDBsComCDI/RegistrarRegate/5
        public async Task<IActionResult> RegistrarResgate(int? id)
        {
            CDBComCDI cdbComCDI;
            if (id == null ||
                (cdbComCDI = await GetCDBComCDIAsync(id.Value)) == null)
                return NotFound();

            return View();
        }

        // POST: CDBsComCDI/RegistrarRegate/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistrarResgate(int id, CDBComCDIResgateViewModel m)
        {
            CDBComCDI cdbComCDI;
            if ((cdbComCDI = await GetCDBComCDIAsync(id)) == null)
                return NotFound();
            if (!ModelState.IsValid)
                return View(m);
            var resgate = new ResgateCDBComCDI { Data = m.Data, Quantidade = m.Quantidade, CDBComCDIId = cdbComCDI.Id };

            var result = cdbComCDI.PodeAdicionarResgate(resgate);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                    ModelState.TryAddModelError(error.Item1, error.Item2);
                return View(m);
            }
            cdbComCDI.AdicionarResgate(resgate);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: CDBsComCDI/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            CDBComCDI cdbComCDI;
            if (id == null ||
                (cdbComCDI = await GetCDBComCDIAsync(id.Value)) == null)
                return NotFound();

            return View(cdbComCDI);
        }

        // POST: CDBsComCDI/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cdbComCDI = await GetCDBComCDIAsync(id);
            _db.CDBsComCDI.Remove(cdbComCDI);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        
        private async Task<CDBComCDI> GetCDBComCDIAsync(int id)
        {
            var userId = (await GetCurrentUserAsync()).Id;
            return await _db.CDBsComCDI.Include(c => c.Resgates).Where(m => m.UserId == userId && m.Id == id).SingleOrDefaultAsync();
        }
        
        private async Task<List<CDBComCDI>> GetAllCDBsComCDIAsync()
        {
            var userId = (await GetCurrentUserAsync()).Id;
            return await _db.CDBsComCDI.Include(c => c.Resgates).Where(c => c.UserId == userId).ToListAsync();
        }

        private Task<User> GetCurrentUserAsync()
            => _userManager.GetUserAsync(HttpContext.User);
    }
}

src/Msmaldi.Financeiro.Website/Controllers/ResumoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Msmaldi.Financeiro.Website.BusinessLogic.CDB;
using Msmaldi.Financeiro.Website.BusinessLogic.CryptoCurrencies;
using Msmaldi.Financeiro.Website.BusinessLogic.SwingTrade;
using Msmaldi.Financeiro.Website.Data;
using Msmaldi.Financeiro.Website.Entities;
using Msmaldi.Financeiro.Website.Models.ResumoViewModels;

namespace Msmaldi.Financeiro.Website.Controllers
{
    public class ResumoController : Controller
    {
        private readonly FinanceiroDbContext _db;
        private readonly PosicaoConsolidadaCDBComCDIFactory _cdbFactory;
        private readonly PosicaoConsolidadaSwingTradeFactory _swingTradeFactory;
        private readonly PosicaoConsolidadaCryptoCurrencyFactory _cryptoCurrencyFactory;

        public ResumoController(FinanceiroDbContext context,
            PosicaoConsolidadaCDBComCDIFactory cdbFactory,
            PosicaoConsolidadaSwingTradeFactory swingTradeFactory,
            PosicaoConsolidadaCryptoCurrencyFactory cryptoCurrencyFactory)
        {
            _db = context;
            _cdbFactory = cdbFactory;
            _swingTradeFactory = swingTradeFactory;
            _cryptoCurrencyFactory = cryptoCurrencyFactory; 
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await GetUserAsync();

            var ativos = new Ativos(
                user, 
                _cdbFactory,
                _swingTradeFactory,
                _cryptoCurrencyFactory);

            return View(ativos);
        }

        private async Task<User> GetUserAsync()
        {
            var userName = HttpContext.User.Identity.Name;
            var user = await _db.Users.AsNoTracking()
                                .Include(u => u.CDBsComCDI)
                                .Include(u => u.SwingTrades)
                                .Include(u => u.CryptoWallets)
                                .FirstOrDefaultAsync(u => u.UserName == userName);

            return user;
        }
    }
}

src/Msmaldi.Financeiro.Website/Controllers/SwingTradesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Msmaldi.Financeiro.Website.BusinessLogic.SwingTrade;
using Msmaldi.Financeiro.Website.Data;
using Msmaldi.Financeiro.Website.Entities;
using Msmaldi.Financeiro.Website.Models.SwingTradeViewModels;

namespace Msmaldi.Financeiro.Website.Controllers
{
    [Authorize]
    public class SwingTradesController : Controller
    {
        private readonly FinanceiroDbContext _db;
        private readonly UserManager<User> _userManager;
        private readonly PosicaoConsolidadaSwingTradeFactory _swingTradePosFactory;
        
        public SwingTradesController(FinanceiroDbContext context,
            PosicaoConsolidadaSwingTradeFactory swingTradePosFactory,
          UserManager<User> userManager)
        {
            _db = context;
            _userManager = userManager;
            _swingTradePosFactory = swingTradePosFactory;
        }

        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var swingTrades = await _db.SwingTrades.AsNoTracking()
                .Where(c => c.UserId == user.Id)
                .ToListAsync();
            var posicoesSwingTrade = swingTrades
                .Select(st => _swingTradePosFactory.ObterPosicaoConsolidada(st)).ToList();

            return View(posicoesSwingTrade);
        }

        [HttpGet]
        public async Task<IActionResult>  Create()
        {
            await GetStocksAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SwingTradeViewModel m)
        {
            await GetStocksAsync();
            if (ModelState.IsValid)
            {
                var swingTrade = new SwingTrade(m.Symbol, m.Quantidade,
                    m.ValorDeAquisicao, userId: (await GetCurrentUserAsync()).Id);
                _db.SwingTrades.Add(swingTrade);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(m);
        }

        private async Task GetStocksAsync()
        {
            var stocks = await _db.Stocks.ToListAsync();
            ViewBag.Stocks = new SelectList(stocks, "Symbol", "Symbol", null);
        }

        // GET: SwingTrades/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            SwingTrade swingTrade;
            if (id == null ||
                (swingTrade = await GetSwingTradeAsync(id.Value)) == null)
                return NotFound();

            return View(swingTrade);
        }

        // POST: SwingTrades/Delete/5
        [HttpPost, ActionName(nameof(Delete))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var swingTrade = await GetSwingTradeAsync(id);
            _db.SwingTrades.Remove(swingTrade);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private async Task<SwingTrade> GetSwingTradeAsync(long id)
        {
            var userId = (await GetCurrentUserAsync()).Id;
            return await _db.SwingTrades.Where(m => m.UserId == userId && m.Id == id).SingleOrDefaultAsync();
        }

        private Task<User> GetCurrentUserAsync()
            => _userManager.GetUserAsync(HttpContext.User);
    }
}

src/Msmaldi.Financeiro.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Msmaldi.Financeiro.Website</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Financeiro</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Resumo" asp-action="Index">Resumo</a></li>
                    <li><a asp-area="" asp-controller="CDBsComCDI" asp-action="Index">CDBs com CDI</a></li>
                    <li><a asp-area="" asp-controller="SwingTrades" asp-action="Index">Swing Trades</a></li>
                    <li><a asp-area="" asp-controller="CryptoWallet" asp-action="Index">Criptomoedas</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Financeiro</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>